### ISSUE TITLE
Create FAQ page

### ISSUE THREAD

**Issue by Praseetha-KR** [appknox/irene#666] opened 2018-08-08 11:11 UTC
It would be good to have an FAQ page linked from dashboard, with details such as: 
- app file pre-requisites
- how static/dynamic/api/manual scan works
- recurring issues, troubleshooting, etc.

**Comment by yashwin** [comment] 2018-08-09 05:16
Duplicate of #629

**Closed by yashwin** 2018-08-09 05:16 UTC
Labels: type:docs
